from rare_identity_protocol.actions import build_action_payload
from rare_identity_protocol.challenge import (
    build_auth_challenge_payload,
    build_full_attestation_issue_payload,
    build_agent_auth_payload,
    build_platform_grant_payload,
    build_register_payload,
    build_set_name_payload,
    build_upgrade_request_payload,
)
from rare_identity_protocol.crypto import (
    b64url_decode,
    b64url_encode,
    decode_jws,
    generate_ed25519_keypair,
    generate_nonce,
    json_dumps_compact,
    load_private_key,
    load_public_key,
    now_ts,
    public_key_to_b64,
    sign_detached,
    sign_jws,
    verify_detached,
    verify_jws,
)
from rare_identity_protocol.errors import (
    ProtocolError,
    ResourceLimitError,
    SignatureError,
    TokenValidationError,
)
from rare_identity_protocol.expiring_store import ExpiringMap, ExpiringSet
from rare_identity_protocol.name_policy import normalize_name, validate_name
from rare_identity_protocol.tokens import (
    issue_agent_delegation,
    issue_full_identity_attestation,
    issue_public_identity_attestation,
    issue_rare_delegation,
)

__all__ = [
    "ProtocolError",
    "ResourceLimitError",
    "SignatureError",
    "TokenValidationError",
    "ExpiringMap",
    "ExpiringSet",
    "b64url_decode",
    "b64url_encode",
    "decode_jws",
    "generate_ed25519_keypair",
    "generate_nonce",
    "json_dumps_compact",
    "load_private_key",
    "load_public_key",
    "now_ts",
    "public_key_to_b64",
    "sign_detached",
    "sign_jws",
    "verify_detached",
    "verify_jws",
    "build_auth_challenge_payload",
    "build_full_attestation_issue_payload",
    "build_agent_auth_payload",
    "build_platform_grant_payload",
    "build_register_payload",
    "build_action_payload",
    "build_set_name_payload",
    "build_upgrade_request_payload",
    "normalize_name",
    "validate_name",
    "issue_agent_delegation",
    "issue_public_identity_attestation",
    "issue_full_identity_attestation",
    "issue_rare_delegation",
]
